version: '3.8'

services:
  app:
    build: .
    container_name: ecommerce-api
    restart: always
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - mongo-express

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_URI}
      ME_CONFIG_BASICAUTH: false
